version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  backend:
    build: .
    container_name: assetlist_server
    command: npm start
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - redis
    volumes:
      - .:/app

volumes:
  redis_data:
